version: "3.8"
services:
    brickd:
        build: .
        ports:
            - "4223:4223"
        volumes:
            - "/dev/bus/usb:/dev/bus/usb"
        privileged: true
        restart: unless-stopped

